syntax = "proto3";

package awstunnel;

option go_package = "github.com/vitalvas/mqtt-forward/internal/awstunnel/pb";

message Message {
  Type type = 1;
  int32 stream_id = 2;
  bool ignorable = 3;
  bytes payload = 4;
  string service_id = 5;
  repeated string available_service_ids = 6;
  uint32 connection_id = 7;

  enum Type {
    UNKNOWN = 0;
    DATA = 1;
    STREAM_START = 2;
    STREAM_RESET = 3;
    SESSION_RESET = 4;
    SERVICE_IDS = 5;
    CONNECTION_START = 6;
    CONNECTION_RESET = 7;
  }
}
