// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/awstunnel/pb/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Type int32

const (
	Message_UNKNOWN          Message_Type = 0
	Message_DATA             Message_Type = 1
	Message_STREAM_START     Message_Type = 2
	Message_STREAM_RESET     Message_Type = 3
	Message_SESSION_RESET    Message_Type = 4
	Message_SERVICE_IDS      Message_Type = 5
	Message_CONNECTION_START Message_Type = 6
	Message_CONNECTION_RESET Message_Type = 7
)

// Enum value maps for Message_Type.
var (
	Message_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "DATA",
		2: "STREAM_START",
		3: "STREAM_RESET",
		4: "SESSION_RESET",
		5: "SERVICE_IDS",
		6: "CONNECTION_START",
		7: "CONNECTION_RESET",
	}
	Message_Type_value = map[string]int32{
		"UNKNOWN":          0,
		"DATA":             1,
		"STREAM_START":     2,
		"STREAM_RESET":     3,
		"SESSION_RESET":    4,
		"SERVICE_IDS":      5,
		"CONNECTION_START": 6,
		"CONNECTION_RESET": 7,
	}
)

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}

func (x Message_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_awstunnel_pb_message_proto_enumTypes[0].Descriptor()
}

func (Message_Type) Type() protoreflect.EnumType {
	return &file_internal_awstunnel_pb_message_proto_enumTypes[0]
}

func (x Message_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Type.Descriptor instead.
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_awstunnel_pb_message_proto_rawDescGZIP(), []int{0, 0}
}

type Message struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Type                Message_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=awstunnel.Message_Type" json:"type,omitempty"`
	StreamId            int32                  `protobuf:"varint,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Ignorable           bool                   `protobuf:"varint,3,opt,name=ignorable,proto3" json:"ignorable,omitempty"`
	Payload             []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	ServiceId           string                 `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AvailableServiceIds []string               `protobuf:"bytes,6,rep,name=available_service_ids,json=availableServiceIds,proto3" json:"available_service_ids,omitempty"`
	ConnectionId        uint32                 `protobuf:"varint,7,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_awstunnel_pb_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_awstunnel_pb_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_awstunnel_pb_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() Message_Type {
	if x != nil {
		return x.Type
	}
	return Message_UNKNOWN
}

func (x *Message) GetStreamId() int32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Message) GetIgnorable() bool {
	if x != nil {
		return x.Ignorable
	}
	return false
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Message) GetAvailableServiceIds() []string {
	if x != nil {
		return x.AvailableServiceIds
	}
	return nil
}

func (x *Message) GetConnectionId() uint32 {
	if x != nil {
		return x.ConnectionId
	}
	return 0
}

var File_internal_awstunnel_pb_message_proto protoreflect.FileDescriptor

const file_internal_awstunnel_pb_message_proto_rawDesc = "" +
	"\n" +
	"#internal/awstunnel/pb/message.proto\x12\tawstunnel\"\x97\x03\n" +
	"\aMessage\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.awstunnel.Message.TypeR\x04type\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\x05R\bstreamId\x12\x1c\n" +
	"\tignorable\x18\x03 \x01(\bR\tignorable\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceId\x122\n" +
	"\x15available_service_ids\x18\x06 \x03(\tR\x13availableServiceIds\x12#\n" +
	"\rconnection_id\x18\a \x01(\rR\fconnectionId\"\x91\x01\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\x10\n" +
	"\fSTREAM_START\x10\x02\x12\x10\n" +
	"\fSTREAM_RESET\x10\x03\x12\x11\n" +
	"\rSESSION_RESET\x10\x04\x12\x0f\n" +
	"\vSERVICE_IDS\x10\x05\x12\x14\n" +
	"\x10CONNECTION_START\x10\x06\x12\x14\n" +
	"\x10CONNECTION_RESET\x10\aB8Z6github.com/vitalvas/mqtt-forward/internal/awstunnel/pbb\x06proto3"

var (
	file_internal_awstunnel_pb_message_proto_rawDescOnce sync.Once
	file_internal_awstunnel_pb_message_proto_rawDescData []byte
)

func file_internal_awstunnel_pb_message_proto_rawDescGZIP() []byte {
	file_internal_awstunnel_pb_message_proto_rawDescOnce.Do(func() {
		file_internal_awstunnel_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_awstunnel_pb_message_proto_rawDesc), len(file_internal_awstunnel_pb_message_proto_rawDesc)))
	})
	return file_internal_awstunnel_pb_message_proto_rawDescData
}

var file_internal_awstunnel_pb_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_awstunnel_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_awstunnel_pb_message_proto_goTypes = []any{
	(Message_Type)(0), // 0: awstunnel.Message.Type
	(*Message)(nil),   // 1: awstunnel.Message
}
var file_internal_awstunnel_pb_message_proto_depIdxs = []int32{
	0, // 0: awstunnel.Message.type:type_name -> awstunnel.Message.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_awstunnel_pb_message_proto_init() }
func file_internal_awstunnel_pb_message_proto_init() {
	if File_internal_awstunnel_pb_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_awstunnel_pb_message_proto_rawDesc), len(file_internal_awstunnel_pb_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_awstunnel_pb_message_proto_goTypes,
		DependencyIndexes: file_internal_awstunnel_pb_message_proto_depIdxs,
		EnumInfos:         file_internal_awstunnel_pb_message_proto_enumTypes,
		MessageInfos:      file_internal_awstunnel_pb_message_proto_msgTypes,
	}.Build()
	File_internal_awstunnel_pb_message_proto = out.File
	file_internal_awstunnel_pb_message_proto_goTypes = nil
	file_internal_awstunnel_pb_message_proto_depIdxs = nil
}
